name: Test DAGs
description: 'run DAG validations and unit tests'
inputs:
  requirements:
    description: 'relative path to requirements.txt'
    required: false
    default: 'requirements/requirements.txt'
  # Tools
  flake8:
    description: 'run Flake8'
    required: false
    default: 'true'
  black:
    description: 'run Black'
    required: false
    default: 'true'
  pytest:
    description: 'run tests with PyTest'
    required: false
    default: 'true'
  # Settings
  testdir:
    description: 'test directory'
    required: false
    default: 'tests'
  dagsdir:
    description: 'DAGs directory'
    required: false
    default: 'dags'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements }}
        pip check
      shell: bash
    
    - if: ${{ inputs.flake8 == 'true' }}
      name: Lint DAGs with flake8
      run: |
        pip install flake8
        flake8 --ignore E501 ${{ inputs.dagsdir }} --benchmark -v
      shell: bash

    - if: ${{ inputs.black == 'true' }}
      name: Run black for code compliance
      run: |
        pip install pytest-black
        pytest ${{ inputs.dagsdir }} --black --v
      shell: bash

    - if: ${{ inputs.pytest == 'true' }}
      name: Test DAGs with PyTest
      run: |
        pip install pytest
        pytest -v
        pushd ${{ inputs.testdir }}
        python3 -m pytest ${{ inputs.testdir }} -v
        popd
      shell: bash
